### ISSUE TITLE
Issue installing and building in project

### ISSUE THREAD

**Issue by SuperCoolFrog** [Lokeh/bs-most#2]
After installation I attempted to build my project and received the following exception 

> bsb -make-world
> 
> [14/14] Building src/ReactDOMServerRe.mlast.d
> [7/7] Building src/ReactDOMRe.cmj
> Warning: refmt version missing. Please set it explicitly, since we may change the default in the future.
> [1/2] Building src/most.mlast
> FAILED: src/most.mlast 
> /usr/local/lib/node_modules/bs-platform/lib/bsc.exe -pp "/usr/local/lib/node_modules/bs-platform/lib/refmt.exe --print binary"    -w -30-40+6+7+27+32..39+44+45+101 -nostdlib -I '/Users/michael/Projects/ReasonML/my-project/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -c -o src/most.mlast -bs-syntax-only -bs-binary-ast -impl /Users/michael/Projects/ReasonML/my-project/node_modules/bs-most/src/most.re
> File "/Users/michael/Projects/ReasonML/my-project/node_modules/bs-most/src/most.re", line 1, characters 12-13:
> Error: 1274: syntax error, consider adding a `;' before
> 
>   We've found a bug for you!
>   /Users/michael/Projects/ReasonML/my-project/node_modules/bs-most/src/most.re
>   
>   There's been an error running Reason's refmt parser on a file.
>   This was the command:
>   
>   /usr/local/lib/node_modules/bs-platform/lib/refmt.exe --print binary '/Users/michael/Projects/ReasonML/my-project/node_modules/bs-most/src/most.re' > /var/folders/hy/kvvyvvc10vsd8k1bn_dn1htr0000gn/T/ocamlpp73a5a9

node 8.9.1
npm 5.5.1
bsb 2.2.3
bs-most ^0.1.1
react ^16.2.0
react-dom ^16.2.0
reason-react >=0.3.4

Edit: 
When I clone and build manually then link it seems to work

**Comment by lilactown** [comment]
@SuperCoolFrog I just published bs-most@1.1.2 to npm - my local tests show that this fixed it. Can you confirm that this fixes the issue?

**Comment by SuperCoolFrog** [comment]
Yep looks good thanks
