### ISSUE TITLE
Update release package

### ISSUE THREAD

**Issue by andresrgz** [Lokeh/bs-most#6]
Current release package does not match the contents of this repository.

For example, this [line](https://github.com/Lokeh/bs-most/blob/master/src/most.re#L106) has the `Js.boolean` type when I download the current release package, while on this repository that line has the `bool` type.

**Comment by lilactown** [comment]
You know when you put something on your TODO list and then immediately forget about it? 😓Sorry about that, that must have been a frustrating thing to troubleshoot. I've published the latest in master as v1.0.0 on npm - let me know if you have any other issues.

**Comment by andresrgz** [comment]
No worries! Everything works fine now. 🙂
